print("write the first number")
a= input()
print("write the operator which we want to use ")
b= input()
print("write the second number")
c= input()
x= eval(a+b+c)
print("the answer is ")
print(x)